//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personal
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public string ToMeet { get; set; }
        public string FromWhere { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string GateNumber { get; set; }
        public string VisitorPassNumber { get; set; }
        public Nullable<System.DateTime> ValidUpTo { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Asset { get; set; }
        public string Email { get; set; }
    }
}
