//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestCamEntities : DbContext
    {
        public TestCamEntities()
            : base("name=TestCamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Picture> tbl_Picture { get; set; }
        public virtual DbSet<tbl_GateNumber> tbl_GateNumber { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
    }
}
